apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-05-17T12:34:17Z"
  generation: 2
  labels:
    app: spring-petclinic-rest-with-recreate-strategy
  name: spring-petclinic-rest-with-recreate-strategy
  namespace: default
  resourceVersion: "10608"
  uid: 9b6dd977-bcc5-40ad-a1e7-4e1431b2d5a1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-rest-with-recreate-strategy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-rest-with-recreate-strategy
    spec:
      containers:
      - image: docker.io/springcommunity/spring-petclinic-rest:3.0.2
        imagePullPolicy: IfNotPresent
        name: spring-petclinic-rest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-17T12:34:49Z"
    lastUpdateTime: "2024-05-17T12:34:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-17T12:34:17Z"
    lastUpdateTime: "2024-05-17T12:34:49Z"
    message: ReplicaSet "spring-petclinic-rest-with-recreate-strategy-6f757454d8"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
