apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T22:02:20Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1892"
  uid: 6c5ddecf-8667-429a-a606-8a3b5c091fa6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.177.90
  clusterIPs:
  - 10.103.177.90
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31732
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
